env: "local"
http_server:
  address: "localhost:8085"
  read_timeout: 4s
  write_timeout: 5s
  idle_timeout: 60s
  graceful_shutdown_timeout: 10s
postgres:
  host: "localhost"
  port: "5432"
  username: "postgres"
  db_name: "postgres"
  ssl_mode: "disable"
  max_open_conns: 100
  max_idle_conns: 2
  max_lifetime: 1h
  driver_name: "postgres"